CREATE TABLE "user" (
  id BIGINT PRIMARY KEY,
  place_id BIGINT NOT NULL REFERENCES place(id),
  created_at TIMESTAMP NOT NULL,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  email VARCHAR(50) NOT NULL UNIQUE,
  animal_id BIGINT NOT NULL REFERENCES animal(id),
)

CREATE TABLE animal (
  id BIGINT PRIMARY KEY,
  name VARCHAR(100)
)

ALTER TABLE animal DROP COLUMN name;
ALTER TABLE animal ADD COLUMN name;
ALTER TABLE animal RENAME COLUMN name TO nickname;
